### PR TITLE
fix: Allow user specified resource attributes

### LINKED ISSUE #151: Cannot specify resource level attributes when initializing the distro
**Versions**
Latest

**Steps to reproduce**
1. Initialize a `new HoneycombSDK`.
2. Try to set a resource:
```
  const sdk = new HoneycombSDK({
    resource: new Resource({
      myAttribute: "my-attribute-value",
    }),
  });
```

3. The attribute does not get set on the resource.

**Additional context**
The[ resource builder](https://github.com/honeycombio/honeycomb-opentelemetry-node/blob/main/src/resource-builder.ts#L10) is called when [initializing the SDK](https://github.com/honeycombio/honeycomb-opentelemetry-node/blob/main/src/opentelemetry-node.ts#L21) and it overwrites anything that's passed in by the user. 

To fix this, we'll have to merge anything provided by the user with the attributes specified in the resource-builder.

### PR DESCRIPTION
**Pull request by pkanal**
## Which problem is this PR solving?

- Closes #151 

## Short description of the changes
- Changed the Resource builder to merge with any resources passed in when initializing the distro
- Added tests
- Added examples

## How to verify that this has the expected result
1. Run the express or typescript express example
2. Set API keys so that data is being sent to Honeycomb (console spans don't seem to expand resource attributes and they show up as `resource: Resource { attributes: [Object] }`
3. Check in honeycomb to see if there's a `global.build_id` attribute on spans

### CODE REVIEW

File: src/resource-builder.ts [hunk 1]
```diff
@@ -1,14 +1,15 @@
...
  * added resource attributes specific to the Honeycomb Distro
  * @returns a Resource instance
  */
-export function configureHoneycombResource(): Resource {
+export function configureHoneycombResource(opts?: HoneycombOptions): Resource {
   return new Resource({
     'honeycomb.distro.version': VERSION,
     'honeycomb.distro.runtime_version': process.versions.node,
-  });
+  }).merge(opts?.resource ? opts.resource : null);
```
Comment (pkanal) [inline src/resource-builder.ts:14]: This looks awful but I wanted to use the `merge` function which either takes a `Resource` type or `null` 😭

**Review by emilyashley — APPROVED** [review]
While I was here I went ahead and added some service name clarification to the examples so they go to the expected datasets. Looks good to me! Thanks.
